Repository redhat-developer/odo-init-image, pull requests merged in 2019-09, with the labels that each got.

#27 Use custom innerloop scripts for java and nodejs
  Dockerfile
  assemble-and-restart
  get-language/getlanguage.go
  language-scripts/image-mappings.json
  language-scripts/java/dev-assemble
  language-scripts/java/dev-run
  language-scripts/nodejs/dev-assemble
  language-scripts/nodejs/dev-run
  run
Labels: approved, lgtm, size/L

#31 Adding more labels required to build image on osbs
  Dockerfile
Labels: approved, lgtm, size/S

#32 update odo init image test jobs
  .travis.yml
Labels: approved, lgtm, size/M

#34 Owner file cleanUp
  OWNERS
Labels: approved, lgtm, size/S

#35 Replace dumb-init with go init
  Dockerfile
  go-init/LICENSE
  go-init/README.md
  go-init/main.go
  scripts/update-vendor.sh
  vendor/dumb-init/CONTRIBUTING.md
  vendor/dumb-init/Dockerfile
  vendor/dumb-init/MANIFEST.in
  vendor/dumb-init/Makefile
  vendor/dumb-init/README.md
  vendor/dumb-init/VERSION
  vendor/dumb-init/VERSION.h
  vendor/dumb-init/ci/artifact-upload
  vendor/dumb-init/ci/docker
  vendor/dumb-init/ci/docker-deb-test
  vendor/dumb-init/ci/docker-python-test
  vendor/dumb-init/ci/docker-tox-test
  vendor/dumb-init/ci/gcov-build
  vendor/dumb-init/ci/gcov-report
  vendor/dumb-init/circle.yml
  vendor/dumb-init/debian/.gitignore
  vendor/dumb-init/debian/changelog
  vendor/dumb-init/debian/clean
  vendor/dumb-init/debian/compat
  vendor/dumb-init/debian/control
  vendor/dumb-init/debian/copyright
  vendor/dumb-init/debian/docs
  vendor/dumb-init/debian/help2man
  vendor/dumb-init/debian/install
  vendor/dumb-init/debian/lintian-overrides
  vendor/dumb-init/debian/manpages
  vendor/dumb-init/debian/rules
  vendor/dumb-init/debian/source/format
  vendor/dumb-init/dumb-init.c
  vendor/dumb-init/pytest.ini
  vendor/dumb-init/requirements-dev.txt
  vendor/dumb-init/setup.py
  vendor/dumb-init/testing/__init__.py
  vendor/dumb-init/testing/print_signals.py
  vendor/dumb-init/tests/__init__.py
  vendor/dumb-init/tests/child_processes_test.py
  vendor/dumb-init/tests/cli_test.py
  vendor/dumb-init/tests/conftest.py
  vendor/dumb-init/tests/exit_status_test.py
  vendor/dumb-init/tests/proxies_signals_test.py
  vendor/dumb-init/tests/shell_background_test.py
  vendor/dumb-init/tests/test-zombies
  vendor/dumb-init/tests/tty_test.py
  vendor/dumb-init/tox.ini
Labels: approved, lgtm, size/XXL

#36 add nodejs minishift images in language mapping
  language-scripts/image-mappings.json
Labels: approved, lgtm, size/XS

#38 set JAVA_OPTIONS in java dev-run
  language-scripts/java/dev-run
Labels: approved, lgtm, size/XS

#39 update version label to match current version
  Dockerfile
Labels: approved, lgtm, size/XS
